name: mahakka
description: An app using the memo protocol to publish content to the BCH blockchain.
publish_to: 'none'
version: 3.6.1-BCH+2025092908

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  translator: ^1.0.4+1
  badges: ^3.1.2
  flutter_native_splash: ^2.4.6
  flutter_confetti: ^0.5.1
  cupertino_icons: ^1.0.8
  pretty_qr_code: ^3.5.0
  bip39_mnemonic: ^4.0.1
  clipboard: ^2.0.2
  html: ^0.15.6
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  youtube_player_flutter: ^9.1.2
  #webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  telegram: ^1.0.0
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.1
  linkify: ^5.0.0
  url_launcher: ^6.3.2
  http: ^1.5.0
  provider: ^6.1.5+1
  uuid: ^4.5.1
  intl: ^0.20.2
  expandable_text: ^2.3.0
  share_plus: ^12.0.0
  zoom_pinch_overlay: ^1.4.3
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.5
  bitcoin_base: ^6.9.0
  any_link_preview: ^3.0.3
  blockchain_utils: ^5.2.0
  background_json_parser: ^1.0.7
  json5: ^0.8.2
  json_path: ^0.7.6
  path: ^1.9.1
  json_annotation: ^4.9.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  isar_community: ^3.3.0-dev.1  # Correct package name
  isar_community_flutter_libs: ^3.3.0-dev.1  # Correct package name
  file_picker: ^10.3.3
  video_player: ^2.10.0
  chewie: ^1.13.0
  flutter_svg: ^2.2.1
  flutter_avif: ^3.1.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0-dev.1  # Correct package name
  icons_launcher: ^3.0.2
  test: ^1.25.0
  mockito: ^5.4.0
  mocktail: ^1.0.4
  firebase_core_platform_interface: ^6.0.1
  cloud_firestore_platform_interface: ^7.0.2
  fake_cloud_firestore: ^4.0.0

icons_launcher:
  image_path: "assets/icon_launcher_1024.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon_launcher_1024.png"
      #notification_image: "assets/icon_round_1010.png"
      #adaptive_background_color: '#000000'
      adaptive_background_image: "assets/icon_launcher_1024.png"
      adaptive_foreground_image: "assets/icon_launcher_1024.png"
      adaptive_round_image: "assets/icon_launcher_1024.png"

flutter:
  uses-material-design: true
  assets:
    - telegram.env
    - assets/
    - assets/images/
    - shorebird.yaml

  fonts:
    # Source Sans 3 - Main UI font for publications and body text
    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/SourceSans3/SourceSans3-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSans3/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSans3/SourceSans3-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SourceSans3/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSans3/SourceSans3-Bold.ttf
          weight: 700

    # JetBrains Mono - For hashtags, code snippets, technical elements
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
          weight: 700

    # Cascadia Code - Alternative monospace for variety or specific use cases
    - family: Cascadia Code
      fonts:
        - asset: assets/fonts/CascadiaCode/CascadiaCode-Light.ttf
          weight: 300
        - asset: assets/fonts/CascadiaCode/CascadiaCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/CascadiaCode/CascadiaCode-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/CascadiaCode/CascadiaCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/CascadiaCode/CascadiaCode-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#000000"
  image: assets/mahakka_gold_round_1024.png
  #branding: assets/branding-development.png
  color_dark: "#000000"
  image_dark: assets/mahakka_gold_round_1024.png
  #branding_dark: assets/branding-development.png

  android_12:
    image: assets/mahakka_gold_round_1024.png
    icon_background_color: "#000000"
    image_dark: assets/mahakka_gold_round_1024.png
    icon_background_color_dark: "#000000"

  web: false